### ISSUE TITLE
Establish data structure

### ISSUE THREAD

**Issue by piperhaywood** [GemCopeland/personal-website#1]
This is going to be kind of irrelevant for `/writing`, it’s more important for the homepage / CV.

See rough lists below based on the current design. I’m using [schema.org](https://schema.org) terms for the time being, and a lot might not be strictly necessary but are worth discussing.

---

Relevant for homepage/footer or just generally (see [schema.org/person](https://schema.org/person)):

- `affiliation`
- `colleagues` (or maybe `follows`?)
- `email`
- `hasCredential`
- `hasOccupation`
- `hasOfferCatalog`
- `jobTitle`
- `knowsAbout`
- `memberOf`
- `name`
- `telephone`
- `workLocation`
- `worksFor`
- `description`
- `image`
- `sameAs`

Would need to figure out how to work in past employment / events. Might be that we actually define the homepage as a `WebPage` `itemtype` with `Person` (the site owner, @GemCopeland in this case obvi!) as the `about` and  `author` properties.

Other types that may be relevant for this site:

- [Organization](https://schema.org/Organization) (for past employers)
- [Event](https://schema.org/Event) (for past residencies, etc.)
- [Article](https://schema.org/Article) (for case studies)
- [Blog](https://schema.org/Blog) and [BlogPosting](https://schema.org/BlogPosting)

Shouldn’t do all of it because that will be prohibitive, but we can use schema.org as a jumping off point at least.

**Comment by GemCopeland** [comment]
Sounds grrrreat

**Comment by piperhaywood** [comment]
Have established rough structured data as part of #23. Needs to be refined somewhat, and need to hook up schema markup. But am closing this issue since we’ve agreed on the high-level elements.
