### ISSUE TITLE
Centre align forward / back arrows at the end of an article

### ISSUE THREAD

**Issue by GemCopeland** [GemCopeland/personal-website#109]
Currently they're still left aligned:
<img width="1552" alt="Screenshot 2022-12-17 at 12 41 26" src="https://user-images.githubusercontent.com/2996847/208242449-ceaa161a-77ef-47d4-9bb1-b46b8866b3da.png">

Would be good if they're in the centre, aligned to the sides of the article text.

**Comment by melnyczuk** [comment]
Should I just do this in the same PR?

**Comment by GemCopeland** [comment]
Oh I already merged it
