### ISSUE TITLE
Establish tech stack

### ISSUE THREAD

**Issue by piperhaywood** [GemCopeland/personal-website#14]
@GemCopeland, my initial thinking is:

- [Eleventy](https://www.11ty.io/docs/) for static site generation
- [Are.na](https://www.are.na) for your images, using the API to generate your Thinking content
- [Netlify](https://www.netlify.com) for hosting the site files (not media) and SSL
- [Netlify Functions](https://www.netlify.com/docs/functions/) for API authentication

And of course GitHub for the repo and for the documentation on how to get set up, authorship, etc.

A few relevant Eleventy docs according to conversations we’ve had recently:

- [Frontmatter](https://www.11ty.io/docs/data-frontmatter/)
- [Tutorials](https://www.11ty.io/docs/tutorials/) (indicates how we could extend things in the future, particularly search)

We’d probably use [this repo](https://github.com/11ty/eleventy-base-blog) as a jumping off point, it’s a basic Eleventy blog made by the guy who started Eleventy.

What do you think? If that seems like a decent jumping-off point, I could get the unstyled structure sketched out on a branch so that we can demo it. We should be able to look at all demos in Netlify on dummy URLs once we get it hooked up.

**Comment by GemCopeland** [comment]
All sounds good to me!

**Comment by piperhaywood** [comment]
Established as part of #23. Closing.
