### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by piperhaywood** [GemCopeland/personal-website#15]
Use cases are:

- Previous / next post
- Previous / next page of posts in feed (main feed, tag feed, and search results)

It can probably all be as simple as the forwards / backwards arrow you currently have, but could also be different.

**Comment by piperhaywood** [comment]
How do we think the arrows should work? See #17 for arrow-related discussion.

**Comment by piperhaywood** [comment]
@GemCopeland to choose a bunch of unicode symbols for this. Once chosen, pass issue back to @piperhaywood so that I can implement them in the global.json file

**Comment by GemCopeland** [comment]
Selected symbols for pagination:

**Back**
←
↵
↫
⬱
⬸
⬳
⬿
⤶
⫷

**Forward**
→
↳
↬
➝
➨
⇢
➺
➽
➯
➔
⤷
⫸

**Comment by piperhaywood** [comment]
This is implemented on `dev`
