### ISSUE TITLE
Consider RSS

### ISSUE THREAD

**Issue by piperhaywood** [GemCopeland/personal-website#16]
There are a few considerations here. One is design: where would a link go?

Another is feasibility in terms of the stack (see #14). It should work with Eleventy (see [repo](https://github.com/11ty/eleventy-plugin-rss)) but we should try to configure the build accordingly so that adding RSS isn’t too much of a headache.

Personally, I think it would be cool to include it!

**Comment by piperhaywood** [comment]
Discussed today. Should choose a tech stack that will allow us to do this eventually, but not impt. for the first version. Moving to Future milestone.

**Comment by sambaldwin** [comment]
+1!
