### ISSUE TITLE
“Back to top” button

### ISSUE THREAD

**Issue by piperhaywood** [GemCopeland/personal-website#17]
Adding this since it was a todo on the Readme

**Comment by piperhaywood** [comment]
@GemCopeland Thanks for adding this to the designs. Is the arrow going to be consistent, or were you thinking that there would be a few different “up” arrows that we’d randomly select from?

Also, is this an SVG or are we going with unicode arrows? Latter would be useful if you want it to be randomised since you could then just put an array of these somewhere in the content, probably `/src/_data/global.json`, and switch them whenever you want.

**Comment by piperhaywood** [comment]
@GemCopeland to choose a bunch of unicode symbols for this. Once chosen, pass issue back to @piperhaywood so that I can implement them in the global.json file

**Comment by GemCopeland** [comment]
Selected symbols for _back to top_ arrow:

↟
⇑
⬏
↑
⇡
⟰
⤴

**Comment by piperhaywood** [comment]
Make sure it exists on tag pages
