### ISSUE TITLE
Can we get different image sizes from Are.na?

### ISSUE THREAD

**Issue by piperhaywood** [GemCopeland/personal-website#19]
Issue is that if we pull in a bunch of screenshots for the block hover style, could be an enormous page size

**Comment by freder** [comment]
https://dev.are.na/documentation/blocks#Block52094

looks like there are 3 sizes: `thumb`, `display`, and `original`

**Comment by piperhaywood** [comment]
Love it when other ppl answer questions for me. :) Thx @freder!!
