### ISSUE TITLE
Check font license

### ISSUE THREAD

**Issue by piperhaywood** [GemCopeland/personal-website#25]
Need to double-check the font license to see whether or not we need to include credits in any specific places.

@GemCopeland This is low-priority, but will need to get done at some point. I’m going to assign this to you. Could you update this thread with any info you find, and then we can incorporate it as necessary? Might be that your footer note is sufficient.

**Comment by GemCopeland** [comment]
It's available under a SIL Open Font License, so (as far as I can tell) as long as I'm not selling it I can use it as I wish.

**Comment by piperhaywood** [comment]
Cool! Will mark this as closed then
