### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by piperhaywood** [GemCopeland/personal-website#27]
The initial designs indicated a footer across the whole homepage, but I don’t think we can achieve this without some really hacky stuff. Have currently hooked it up so that it resides beneath the “homepage” panel on large screens.

To review / discuss!

**Comment by piperhaywood** [comment]
@GemCopeland will review designs based on current version

**Comment by GemCopeland** [comment]
@piperhaywood I updated the footer in Figma to only take up half the screen width. I couldn't remember what happens to it on the blog pages – can it stretch the full width there? Perhaps let's just discuss on the weekend.

**Comment by GemCopeland** [comment]
The max-width of the footer prose should be around 400px. On the homepage, the `Friends` and `Credits` columns should be side-by-side. Let's discuss so I can understand how to fix this myself.
