### ISSUE TITLE
Date needs to align with baseline of activity

### ISSUE THREAD

**Issue by GemCopeland** [GemCopeland/personal-website#40]
Very small thing, but could you align the baseline of the small date with the baseline of the rest of the text?

<img width="427" alt="Screenshot 2019-10-29 08 59 17" src="https://user-images.githubusercontent.com/2996847/67752226-8cd74780-fa2a-11e9-9c1e-48c738528012.png">

**Comment by piperhaywood** [comment]
Sure! Done on `dev`
