### ISSUE TITLE
Write Privacy policy

### ISSUE THREAD

**Issue by GemCopeland** [GemCopeland/personal-website#43]

**Comment by GemCopeland** [comment]
@piperhaywood Hmm, I don't think I need anything more than what I have in the footer, seeing as I'm intentionally not using any analytics.

```Your data isn’t collected when using this site. If you switch to high contrast mode, the site sets up a cookie to remember your preference. This cookie expires in one year.```

**Comment by piperhaywood** [comment]
The only other thing would be Netlify’s server logs. You’re not using Netlify Analytics so it’s not something that you’ll have access to, but technically Netlify will be collecting visitors’ IP addresses and browser / device info. I’ve seen some people list this in their policies, others do not. Up to you!
