### ISSUE TITLE
Markdown formatting on Arena excepts

### ISSUE THREAD

**Issue by GemCopeland** [GemCopeland/personal-website#44]
Is there a way we can display the correct formatting on the Arena `Info` excepts?

<img width="693" alt="Screenshot 2019-10-29 09 15 38" src="https://user-images.githubusercontent.com/2996847/67753612-e3458580-fa2c-11e9-8836-c766be7ad583.png">

**Comment by piperhaywood** [comment]
Yep, just won't be able to have the links there since the whole block is linked.

**Comment by piperhaywood** [comment]
This is implemented on the `dev` branch that we’ll review together.
