### ISSUE TITLE
Hidden-by-default “skip” buttons

### ISSUE THREAD

**Issue by piperhaywood** [GemCopeland/personal-website#5]
This will probably just include “skip to main content” near the top and “back to top” after each post. Could simply look the same as the “read more” button, just need to know where they should go if/when they’re tabbed to.

Related to #4

**Comment by GemCopeland** [comment]
Added design to Figma

**Comment by piperhaywood** [comment]
Should also do a “Skip to contrast adjustment” and “back to top” after the contrast adjuster.

**Comment by piperhaywood** [comment]
Fixed in v0.3
