### ISSUE TITLE
Accessibility enhancements

### ISSUE THREAD

**Issue by piperhaywood** [GemCopeland/personal-website#6]
This issue is to collect ideas for accessibility enhancements.

For example, should we include an “increase contrast” toggle in the footer?

**Comment by GemCopeland** [comment]
Just putting this here so I don't forget – we could make the toggle icon a Unicode character, rather than a vector: https://en.wikipedia.org/wiki/Geometric_Shapes

**Comment by GemCopeland** [comment]
Designs are up to date with the enhancements we discussed: contrast toggle, greyscale version, focus states and `skip to content` buttons.
