### ISSUE TITLE
Switch from border-bottom to normal underlines

### ISSUE THREAD

**Issue by piperhaywood** [GemCopeland/personal-website#60]
We’re using `border-bottom` for links right now which is sort of unnecessarily complex. Could instead just use `text-decoration: underline` (fairly standard) with `text-underline-offset`. The offset property is only valid in Firefox and Safari right now, but word on the street is that Chrome will be looking at this before Christmas so probably worth doing. Not valid in Edge right now, but it will still look perfectly fine with normal underlines there.

@GemCopeland What do you think? I’d love to swap TBH because the underline approach feels like technical debt

**Comment by GemCopeland** [comment]
I saw this `text-underline-offset` thing on Twitter. Hilarious that it's taken so long. Definitely down to swap it :)

**Comment by piperhaywood** [comment]
Fixed in v0.3
