### ISSUE TITLE
Re-assess image use w/in Arena blocks

### ISSUE THREAD

**Issue by piperhaywood** [GemCopeland/personal-website#65]
The Thinking and Home pages are getting _pretty_ heavy due to the quantity of images, and since some of the GIFs are kind of large (one is 7.7MB). We’re already getting the smallest thumb available from the Are.na API so can’t go any smaller.

For the time being, I’ll introduce [native lazyloading](https://css-tricks.com/native-lazy-loading/) but that isn’t at all well supported yet. If/when we hook up #11 with a third-party lazyloading script, we could get that in place for better support.

Even if we do lazyloading though, the page size could still get pretty big which isn’t great for bandwidth costs and all that jazz. Probably worth reconsidering the Arena blocks at some point design-wise for this reason. Could go with the single most recent image for each? Or some low-ish number, but laid out in a nifty way?

The only other restriction related to Arena thumbnails that might impact the design, as far as I can think of right now, is their dimensions. Arena thumbs currently have a longest edge of 200px, so we shouldn‘t display them too large.

**Comment by piperhaywood** [comment]
Also the GIFs really are killing things unfortunately!

In Safari, my fans start whirring when I open up the site. If you remove the Spinners channel, it stops.

Regarding the size of the GIFs, I think that Arena might not resize them, or maybe they resize them in a different way. We’re always pulling through the `thumb` image size from the API, but some of the GIFs are actually much larger. [This one](https://d2w9rnfcy7mm78.cloudfront.net/1417254/original_aa09e765df611852c2e3f01d4c6b0bac.gif?1510459648?bc=1) for example, from the Right Click channel, is 900x691px and 7.7MB.

I’m not totally sure what to do about this... we could avoid showing GIFs, but that seems like a bit of a shame. Could instead tweak the design so that it only ever shows a set amount of images per channel, and could potentially randomise the images that are loaded each time. I think that if we do a future phase of development on the site, this should probably be the priority!

**Comment by GemCopeland** [comment]
Hey @melnyczuk, I was looking at the Ecograder report for my site and this issue with the Are.na thumbnails really kills it: https://ecograder.com/report/JgQvGBMpKtEZgWErT63kImWn

It loading all the images from each channel at their full size, makes loads of requests to the server and the layout jumps around as it loads. 

Do you think there's a way to improve this? e.g. Only loading the latest ~10 or so images, no gifs, resizing them way smaller, and potentially starting with placeholder blocks so there's no movement as they load?
