### ISSUE TITLE
Sketch Are.na block hover state

### ISSUE THREAD

**Issue by piperhaywood** [GemCopeland/personal-website#7]
> We spoke about making this more visual but adding a grid of small thumbnails. This would function to add some more visual interest to the page, and give people a better overview of the contents.

**Comment by GemCopeland** [comment]
Added design to Figma

**Comment by piperhaywood** [comment]
Looks good, only question remaining is whether or not we should be truncating excerpts. Reality is that we will need to (there will be a possibility of the text being too long), so would be good to get a character count guidance and then we can go from there.
