### ISSUE TITLE
“Last updated” date in footer seems wrong

### ISSUE THREAD

**Issue by piperhaywood** [GemCopeland/personal-website#77]
@GemCopeland Was just moseying around your site and noticed that the “Last updated” date in the footer is probably wrong, you’ve got more recent writing but the date is August 2020! Not sure what’s going on there... need to investigate. Anyways, raising here to keep track of it!

**Comment by GemCopeland** [comment]
I think it's because that's just manually added by me, rather than generated when I update the site 😂
