### ISSUE TITLE
"Thinking" panel no longer updating

### ISSUE THREAD

**Issue by GemCopeland** [GemCopeland/personal-website#79]
@piperhaywood I've noticed that the "Thinking" panel doesn't update anymore. I've added new channels to the My Website Arena channel, but they don't get pulled into the website. Do you think it's something to do with the Arena API updating?

**Comment by piperhaywood** [comment]
Ack, I didn’t see this till just now @GemCopeland, sorry! Will investigate...

**Comment by piperhaywood** [comment]
Looks like @melnyczuk actually sorted it ? :)

**Comment by GemCopeland** [comment]
Haha yes he did! In house developer with benefits ;)
